#   docker-compose build
#   docker-compose up

version: '3.7'

services:

  web:
    container_name: 'backend'
    image: 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/backend
    ports:
     - "5000:5000"
    depends_on:
     - "my-postgres"
    networks:
      - app-network
  my-postgres:
    container_name: 'my-postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
    networks:
      - app-network
    ports:
     - 5432:5432
    volumes:
     - local_postgres_data:/var/lib/postgresql/data
  nginx:
     container_name: frontend
     image: frontend
     build:
       context: ./frontend
       dockerfile: nginx.dockerfile
     ports:
       - "80:80"
       - "443:443"
       
     networks:
     - app-network
networks:
   app-network:
     driver: bridge
volumes:
  local_postgres_data: {}