#   docker-compose build
#   docker-compose up

version: '3.7'

services:

  web:
    container_name: 'backend'
    image: 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/backend
    ports:
     - "5000:5000"
    networks:
      - app-network
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    networks:
     - app-network
  
  nginx:
     container_name: frontend
     image: frontend
     build:
       context: ./frontend
       dockerfile: nginx.dockerfile
     ports:
       - "80:80"
       - "443:443"
       
     networks:
     - app-network
networks:
   app-network:
     driver: bridge
volumes:
  db_volume: